# Trial Name: demo.yaml
# ARIAC2023
# 2023-03-01 20:09:30

# ENVIRONMENT SETUP
time_limit: -1 # options: -1 (no time limit) or number of seconds

kitting_trays: # Which kitting trays will be spawned
  tray_ids: [0, 5]
  slots: [5, 2]

parts:
  agvs:
    agv1:
      tray_id: 5
      parts:
      - type: 'pump'
        color: 'blue'
        quadrant: 3
        rotation: pi/2
      - type: 'regulator'
        color: 'purple'
        quadrant: 4
        rotation: 0.9
    agv3:
      tray_id: 6
      parts:
      - type: 'battery'
        color: 'red'
        quadrant: 1
        rotation: pi/4

  bins: # bin params - 8 total bins each bin has nine total slots (1-9)
    bin1:
      - type: 'battery'
        color: 'orange'
        slots: [1,3,5,7,9]
        rotation: pi
        flipped: true
    bin4:
      - type: 'sensor'
        color: 'green'
        slots: [2,4,7]
        rotation: pi/5

  conveyor_belt: #population params for conveyor belt
    active: true
    spawn_rate: 10 # seconds between spawn
    order: sequential # random or sequential
    parts_to_spawn:
      - type: 'regulator'
        color: 'orange'
        number: 15
        offset: -0.7 # between -1 and 1
        rotation: pi/2

# ORDER SETUP
orders:
  - id: 'S1J16KPE'
    type: 'kitting'
    announcement:
      part_type: 'battery'
      part_color: 'red'
      agv: 1    priority: false
    kitting_task:
      agv_number: 3
      tray_id: 7
      destination: 'assembly_front'
      products:
        - type: 'pump'
          color: 'blue'
          quadrant: 4
  - id: 'GY3OMF9P'
    type: 'assembly'
    announcement:
      submission_condition:
        order_id: 'S1J16KPE'
    priority: false
    assembly_task:
      agv_number: [3]
      station: 'as4'
      products:
        - type: 'regulator'
          color: 'purple'
          assembled_pose: # relative to briefcase frame
            xyz: [0.175, -0.223, 0.215]
            rpy: ['pi/2', 0, '-pi/2']
          assembly_direction: [0, 0, -1]

# GLOBAL CHALLENGES
challenges:
  - robot_malfunction:
      duration: 14.0
      robots_to_disable: ['floor_robot', 'ceiling_robot']
      time: 21.0
  - faulty_part:
      order_id: 'GY3OMF9P'
      quadrant: [1, 3]
  - dropped_part:
      robot: 'ceiling_robot'
      type: 'regulator'
      color: 'orange'
      drop_after_num: 10 # first part the robot successfully picks
      drop_after_time: 25.0 # secons
