# Trial Name: demo.yaml
# ARIAC2023
# 2023-03-01 22:02:07

# ENVIRONMENT SETUP
time_limit: -1 # options: -1 (no time limit) or number of seconds

kitting_trays: # Which kitting trays will be spawned
  tray_ids: [4, 5, 3]
  slots: [5, 3, 4]

parts:
  agvs:
    agv1:
      tray_id: 5
      parts:
      - type: 'battery'
        color: 'blue'
        quadrant: 1
        rotation: 'pi'
    agv3:
      tray_id: 7
      parts:
      - type: 'battery'
        color: 'green'
        quadrant: 3
        rotation: 'pi/3'

  bins: # bin params - 8 total bins each bin has nine total slots (1-9)
    bin1:
      - type: 'regulator'
        color: 'orange'
        slots: [2,4,6,8]
        rotation: 'pi/4'
        flipped: true
    bin4:
      - type: 'sensor'
        color: 'green'
        slots: [2,5]
        rotation: 0.9

  conveyor_belt: #population params for conveyor belt
    active: true
    spawn_rate: 15 # seconds between spawn
    order: 'sequential' # random or sequential
    parts_to_spawn:
      - type: 'battery'
        color: 'purple'
        number: 10
        offset: -0.6 # between -1 and 1
        rotation: 'pi/5'