# Trial Name: test.yaml
# ARIAC2023
# 2023-03-01 17:50:43

# ENVIRONMENT SETUP
time_limit: -1 # options: -1 (no time limit) or number of seconds

kitting_trays: # Which kitting trays will be spawned
  tray_ids: [0, 5, 9]
  slots: [1, 4, 6]

parts:
  agvs:
    agv1:
      tray_id: 4
      parts:
      - type: 'sensor'
        color: 'green'
        quadrant: 1
        rotation: 0

  bins: # bin params - 8 total bins each bin has nine total slots (1-9)
    bin1:
      - type: 'sensor'
        color: 'green'
        slots: [4,8]
        rotation: 0
        flipped: true

  conveyor_belt: #population params for conveyor belt
    active: true
    spawn_rate: 0 # seconds between spawn
    order: sequential # random or sequential
    parts_to_spawn:
      - type: 'sensor'
        color: 'green'
        number: 0
        offset: 0.45 # between -1 and 1
        rotation: 0

# ORDER SETUP
orders:
  - id: 'B3POEKP8'
    type: 'kitting'
    announcement:
      time_condition: 0.0
    priority: false
    kitting_task:
      agv_number: 1
      tray_id: 0
      destination: 'warehouse'
      products:
        - type: 'sensor'
          color: 'green'
          quadrant: 1
