# Trial Name: test.yaml
# ARIAC2023
# 2023-02-28 15:32:15

# ENVIRONMENT SETUP
time_limit: 0 # options: -1 (no time limit) or number of seconds

kitting_trays: # Which kitting trays will be spawned
  tray_ids: [0]
  slots: [1]

parts:
  agvs:
    agv4:
      tray_id: 4
      parts:
      - type: 'pump'
        color: 'orange'
        quadrant: 3
        rotation: 'pi/2'
      - type: 'sensor'
        color: 'green'
        quadrant: 2
        rotation: 'pi'

  bins: # bin params - 8 total bins each bin has nine total slots (1-9)
    bin2:
      - type: 'battery'
        color: 'green'
        slots: [1,3,5,7]
        rotation: 0
        flipped: false
    bin3:
      - type: 'regulator'
        color: 'purple'
        slots: [4]
        rotation: 0
        flipped: true

  conveyor_belt: #population params for conveyor belt
    active: true
    spawn_rate: 5 # seconds between spawn
    order: sequential # random or sequential
    parts_to_spawn:
      - type: 'regulator'
        color: 'orange'
        number: 10
        offset: -1 # between -1 and 1
        rotation: pi/3
        # time_before_next_part: 2 # seconds
      - type: 'sensor'
        color: 'red'
        number: 6
        offset: 0 # between -1 and 1
        rotation: 0
        # time_before_next_part: 2 # seconds

# ORDER SETUP
orders:
  - id: 'FRU05FOH'
    type: 'kitting'
    announcement:
      time_condition: 0.0
    priority: false
    kitting_task:
      agv_number: 1
      tray_id: 0
      destination: 'warehouse'
      products:
        - type: 'battery'
          color: 'blue'
          quadrant: 1
        - type: 'battery'
          color: 'blue'
          quadrant: 3

# GLOBAL CHALLENGES
challenges:
  - sensor_blackout:
    duration: 0.0
    sensors_to_disable: []
      time: 0.0
