name: ARIAC Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:iron-desktop
    steps:
    - uses: actions/checkout@v4
    - name: Setup colcon workspace
      id: configure
      run: |
        cd ..
        mkdir -p /home/ariac_ws/src
        cp -r ARIAC /home/ariac_ws/src/
        apt-get update && apt-get upgrade -q -y
        apt-get update && apt-get install -q -y --no-install-recommends \
          python3-colcon-ros
        apt-get install python3-pip -y
        pip install setuptools==58.2.0
        cd /home/ariac_ws/src/
        rosdep update
        rosdep install --from-paths ./ -i -y --rosdistro iron \
          --ignore-src
    - name: Build project
      id: build
      run: |
        cd /home/ariac_ws/
        . /opt/ros/iron/local_setup.sh
        colcon build
