name: ARIAC Build

on: push

jobs:
  build_docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    steps:
      - uses: ros-tooling/setup-ros@v0.5
        with:
          required-ros-distributions: galactic
      - run: "source /opt/ros/galactic/setup.bash && ros2 run --help"
