name: ARIAC Build

on: push

jobs:
  build_docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
      - uses: ros-tooling/setup-ros@v0.5
        with:
          required-ros-distributions: noetic humble
      - run: "source /opt/ros/humble/setup.bash && ros2 run --help"
      - run: "source /opt/ros/noetic/setup.bash && rosnode --help"
